name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export TAG=casai/pg-dump-s3:$(date +%s)
        docker build ./src/ --file ./src/Dockerfile --tag $$TAG
